### ISSUE TITLE
Drupal version status

### ISSUE THREAD

**Issue by Pasqualle** [hugovk/drupal-release-cycle#6]
Show a different color when the given version is in "Active support" vs "Security fixes only"
https://www.drupal.org/project/drupal/issues/2917655#comment-13426566

**Comment by hugovk** [comment]
Thanks for the issues, I only just noticed I wasn't automatically watching this repo, perhaps because it's a fork.

We already have different colours:

* red: dead
* orange: security
* green: bugfix
* blue: prerelease

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/1324225/195281242-4903288a-8e17-4ba4-860f-be966cdc780f.png">
